language: go
sudo: false
go:
  - tip
env:
  - GO111MODULE=on
git:
  depth: 1
os:
  - linux
dist: xenial
install: true
matrix:
  fast_finish: true
notifications:
  email: false
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/ | grep -v /proto/)
  - go install -mod=vendor github.com/fzipp/gocyclo
  - go install -mod=vendor golang.org/x/lint/golint
  - go install -mod=vendor github.com/mattn/goveralls
script:
  - go test -v -race -mod=vendor ./...
  - go vet -mod=vendor ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list -mod=vendor ./...)
  - goveralls -service=travis-ci