dist: xenial
language: go
go:
- tip
env:
  matrix:
  - GO111MODULE=on
  global:
  - secure: kg7sUnGHZD0U7SdxRlf/DSysb0SOz8kjSaS8h9fVv9xScrgJqPAYlZLbfxzyJU3kTv67JHSYM2vSrOndLEi7U1rQxseVCf2GrLKQmAxmc3K/9LdDytGd3/1l+eCodW9+wObYFPuWDc540xWO6WClNfhRC0V4VBL6pry7TB4O1p8MsQky6xaX/7eEHec+v7sVRtLG1aH/UpzuhScgXWFVOZ8dOZviKLLxOxTA6tQfWJsNNg1YSabLOgBm+3Sa8TsYAnUdqAVJMSNr91Z09BqDBJMF1el8Sp3zxQhZIQGUlmyOw1e6kkkxuHuGhbueFG8NID5hJFveC/rByV9aI00i00pvU8YTOsuahmj+QAbf6g0b821WaDvLse2A0+S8XUZWyyUkerPQ9Uwke5YafuybCac4Q2yqt2LS70HjQkSuFmiWR9X/TjMSsf0+mb/R8ubcN1JqmDj+INjnKBZoPEvK3bl9Kqa2Ic8DmYiksR7Ni39TLXA1P1YhShhmg2XpE3WS6I2sQPKgs12PZeI6F9WfergFMjDw1hZxH9fjhJAkP/5a2KC1ev1QaVK3PO3nju5VRK4A9Iks3zqNkK9h5+z9NqML4l6BllwGpeRuymKMiIBNZc8TaUgBA1+crfj67Cqxf2Rm3SxkzRuiXUDpbKsj4A/+nXlu7U9s7SmWADp0iLA=
  - secure: rpIMWb8j+8xk33Wd7jkB3Yi4ZXpJ6Gk3OpPb2M4t9ivWymG0r9lDMUOomC1rdgTdUyFFZJbq6oid8zUiqidltyu6UGP/d96WY0vj/P4BBX10fOWqtKDdJxU9eMZQdgvLTRnm8cWzYBZkGgmOfmJk5qqd7W0ts/XdQUeAgIDcwJ6L/7oiz/XxahwwoPcHSlMbNAJvwCZjXO3u+ynQ699jWFEiXQA1SYgWEsJgvkltt2bLCnfWeppMPSzSyoeCzmHPWPS9rcEr/Px3VU4Dv7zTgf8fxA7ojD+GRYsjCtaRd3mFhZ4hxSFzCLqERIyIUrFXAxBYA1AULBldZ5vYgb82k68fI0UTr4gu5yLFj+wi6NV2qJTvJOsJd6P0KxevMw2IqBC4ipz/QNCuw7rcXpjaq5MH1bh3H7qHb5FkSPKhL1KcCoxCEiF9NLHAbCCzpE88MjZMkP0o3y+Uw7EWi2ErqNyeMfq6D6GKEwGKIQNIYhoHKIWhFlHZcphFid4oGxvb2vxheM4vYcexPEZxv71NI/l2fyyIDNOOu3CqVL0YCYgFV6f5/JBGzYC088Wn5zsLd6ZxUUfYkV2lQwpjooY2EXvMaTKRhrnlCzmkpOyh3IiJHNhUZu+5+4T9GNEGoLqrMPoOoLIhANVutEw9dlXHQL1gYsS0wh9HTEl74xW8Llg=
git:
  depth: 1
install: true
matrix:
  fast_finish: true
notifications:
  email: false
before_script:
- go install github.com/golangci/golangci-lint/cmd/golangci-lint
- go install github.com/mattn/goveralls
script:
- go test -v -race ./...
- golangci-lint run --no-config --issues-exit-code=0 --deadline=30m --disable-all
  --enable=deadcode  --enable=gocyclo --enable=golint --enable=varcheck --enable=structcheck
  --enable=maligned --enable=errcheck --enable=dupl --enable=ineffassign --enable=interfacer
  --enable=unconvert --enable=goconst --enable=gosec --enable=megacheck
- goveralls -service=travis-ci
- docker build -t kostiamol/centerms:latest .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push kostiamol/centerms:latest
