language: go
sudo: false
go:
- 1.9
- tip
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
notifications:
  email: false
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get github.com/golang/lint/golint
- go get honnef.co/go/tools/cmd/megacheck
- go get github.com/fzipp/gocyclo
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v -race ./...
- gocyclo -over 19 $GO_FILES
- "$GOPATH/bin/goveralls -service=travis-ci"
deploy:
  provider: heroku
  api_key:
    secure: J9/tuta3IloCIYMbMSrArBlO/2+RifW4GDXM6VH/V/1EO8Mt4aw9YdCAXxPtDMOgbR2QP8IipxrXauSJw9dbfgFDuuzz7/TSpufWfcGQw/4HrZSS9hy6Abey4adgg6dpTtyKEXw+XsPgvul6RyO/AVcFcfSgUYstNeHYDuqwcMsL1R7YeQNb2/Z8gk3kGIT1rpF7WKJeS4kIdFtbIJrui70uNsRtQPluz+22v3XDFFJsjBRVHG1l8Q0ccT3GReooxFMv/28R6bs8x4WXlkAL75Vyj/uS3ZKYhaxUZP5+s9Ipapkv2y1FaXxWw3CUDWd5itCK9l4YsSE9cksauPzsyzjvaf6VvNLJSrhAg2G5Z8ccvzDKLzH3dI9XlbP5A90aviM++sMLCwMzoPWYNbW8kQsa8AQuSOxCS/vCXSbaFVmfscswfu86NcBesMaVgEELpcblwHEMecm1nuovAw+6c3qUDSYpqOwr+WDIXWmvqgOAXnAqLjvSll1XvIx5F7wdflrG3nU2LhXaxEiNSNhaJHeINYmWQ9kW11Gnaw46oHUrrMf89I1/Oen42F5rw/7ZmiJjlxL2xIb+MA7a7N8afOulLWESESbxfFImnK1GTmuZPueeYQXY0L52K6fkK7SGK6DwTyOBvtXhapWMe1gP/XCQ43qOGSdzcoiH2nZ0vas=
  on: master
  app: shms-center