language: go
go:
    - tip
git:
    depth: 1
os:
    - linux
dist: trusty
sudo: false
env:
    - GO111MODULE=on
install: true
matrix:
    fast_finish: true
notifications:
    email: false
before_script:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
    - go install -mod=vendor golang.org/x/lint/golint
    - go install -mod=vendor honnef.co/go/tools/cmd/megacheck
    - go install -mod=vendor github.com/fzipp/gocyclo
    - go install -mod=vendor golang.org/x/tools/cmd/cover
    - go install -mod=vendor github.com/mattn/goveralls
script:
    - go test -v -race ./...
    - go vet ./...
    - gocyclo -over 19 $GO_FILES
    - golint -set_exit_status $(go list ./...)
    - "$GOPATH/bin/goveralls -service=travis-ci"
