language: go
sudo: false
go:
    - tip
matrix:
    allow_failures:
        - go: tip
    fast_finish: true
notifications:
    email: false
before_script:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
    - go get -u golang.org/x/lint/golint
    - go get -u honnef.co/go/tools/cmd/megacheck
    - go get -u github.com/fzipp/gocyclo
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls
script:
    - go test -v -race ./...
    - gocyclo -over 19 $GO_FILES
    - "$GOPATH/bin/goveralls -service=travis-ci"
