language: go
sudo: false
go:
    - tip
matrix:
    fast_finish: true
notifications:
    email: false
before_script:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
    - go get -u golang.org/x/lint/golint
    - go get -u honnef.co/go/tools/cmd/megacheck
    - go get -u github.com/fzipp/gocyclo
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls
script:
    - env GO111MODULE=on go test -v -race ./...
    - env GO111MODULE=on go vet ./...
    - env GO111MODULE=on gocyclo -over 19 $GO_FILES
    - env GO111MODULE=on golint -set_exit_status $(go list ./...)
    - "$GOPATH/bin/goveralls -service=travis-ci"
