language: go
sudo: false
go:
  - tip
env:
  - GO111MODULE=on
git:
  depth: 1
os:
  - linux
dist: xenial
install: true
matrix:
  fast_finish: true
notifications:
  email: false
before_script:
  - go install -mod=vendor github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install -mod=vendor github.com/mattn/goveralls
script:
  - go test -v -race -mod=vendor ./...
  - golangci-lint run --no-config --issues-exit-code=0 --deadline=30m \
    --disable-all --enable=deadcode  --enable=gocyclo --enable=golint --enable=varcheck \
    --enable=structcheck --enable=maligned --enable=errcheck --enable=dupl --enable=ineffassign \
    --enable=interfacer --enable=unconvert --enable=goconst --enable=gosec --enable=megacheck
  - goveralls -service=travis-ci