version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

  nats:
    image: nats:latest
    ports:
      - "4222"
    networks:
      - backend

  centerms:
    build: .
    image: centerms
    env_file:
      - .env
    environment:
      - STORE_HOST=redis
      - PUB_HOST=nats
    ports:
      - "8070:8070"
      - "8080:8080"
      - "8090"
    networks:
      - backend
    depends_on:
      - redis
      - nats

networks:
  backend: