version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

  centerms:
    build: .
    image: centerms
    env_file:
      - .env
    ports:
      - "8070:8070"
      - "8080:8080"
      - "8090:8090"
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend: