name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.5.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.5.0
      with:
        tags: kostiamol/centerms:latest
        pull: true
        push: true
