name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: | 
        go test -v ./...
        go test -v -race ./...
        go install github.com/golangci/golangci-lint/cmd/golangci-lint
        golangci-lint run --no-config --issues-exit-code=0 --deadline=30m
          --enable=deadcode  --enable=gocyclo --enable=golint --enable=varcheck --enable=structcheck
          --enable=maligned --enable=errcheck --enable=dupl --enable=ineffassign --enable=interfacer
          --enable=unconvert --enable=goconst --enable=gosec --enable=megacheck
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.5.0
      with:    
        context: .
        push: true
        tags: kostiamol/centerms:latest
